# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
# Use a package of configuration called an orb.
jobs:
  ## Run unit tests
  test_unit:
    working_directory: ~/showfotos

    docker:
      - image: circleci/android:api-29

    steps:
      - checkout
      - run:
          name: Ruby dependencies
          command: bundle check || bundle install --path vendor/bundle

      - run:
          name: Android dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Run unit tests
          command: bundle exec fastlane test