# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
# Use a package of configuration called an orb.
jobs:
  ## Run unit tests
  docker:
      - image: circleci/android:api-29
  test_unit:
    - checkout
    - run:
       name: Ruby dependencies
       command: bundle check || bundle install --path vendor/bundle

    - run:
       name: Android dependencies
       command: ./gradlew androidDependencies
       
    - run:
        name: Run unit tests
        command: bundle exec fastlane test

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      #- welcome/run